Application/mysite/accounts/urls.py
from django import urls
from django.urls import path

from . import views

app_name="accounts"
urlpatterns=[
    path('sign-up', views.SignUpView.as_view(), name='signup'),
    path('profile', views.profile, name='profile')
] 

Application/mysite/musicTribes/urls.py
from django.urls import path

from . import views

app_name='MusicTribes'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_tribe', views.create_tribe, name="create_tribe"),
    path('<int:tribe_id>/', views.detail, name='detail'),
    path('<int:tribe_id>/join_tribe', views.join_tribe, name="join_tribe"),
    path('<int:tribe_id>/add_playlist', views.add_playlist, name="add_playlist"),
    path('<int:playlist_id>/delete_playlist', views.delete_playlist, name="delete_playlist"),
    path('<int:playlist_id>/edit_playlist', views.edit_playlist, name="edit_playlist"),
    path('<int:tribeMember_id>/kick_user', views.kick_user, name="kick_user"),
    path('<int:tribe_id>/add_message', views.add_message, name="add_message"),
    path('<int:message_id>/<int:tribe_id>/delete_message', views.delete_message, name="delete_message"),
    path('<int:playlist_id>/<int:tribe_id>/playlist_detail', views.playlist_detail, name='playlist_detail'),
    path('<int:tribe_id>/<int:playlist_id>/add_track', views.add_track, name="add_track"),
    path('like_track/<int:track_id>', views.like_track, name="like_track"),
    path('<int:track_id>/add_comment', views.add_comment, name='add_comment'),
    path('<int:track_id>/delete_track', views.delete_track, name="delete_track"),
    path('<int:comment_id>/<int:track_id>/delete_comment', views.delete_comment, name="delete_comment"),
]

Application/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from musicTribes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('musicTribes.urls')),
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Application/mysite/musicTribes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class TimeStamped(models.Model):
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField(editable=False)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()

        self.updated_at = timezone.now()
        return super(TimeStamped, self).save(*args, **kwargs)

    class Meta:
        abstract = True

class Tribe(TimeStamped):
    tribeName = models.CharField(max_length=128, unique=True, blank=False)
    tribeLogo = models.ImageField(default='defaultTribeLogo.jpg', upload_to='tribeLogo_pics')
    genre = models.CharField(max_length=128, blank=False)
    chieftain=models.ForeignKey(User, on_delete=models.CASCADE, related_name="username_users") 

    @classmethod
    def tribesChieftain_for(cls, user):
        chieftainTribe=Tribe.objects.filter(chieftain=user)
        return chieftainTribe

    def __str__(self):
        return self.tribeName

class TribeMember(TimeStamped):
    tribe = models.ForeignKey(Tribe, on_delete=models.CASCADE, related_name="tribe", unique=False) 
    member= models.ForeignKey(User, on_delete=models.CASCADE, related_name="member", unique=False) 

    @classmethod
    def tribes_for(cls, user):
        memberships=TribeMember.objects.filter(member=user)
        myTribes=[x.tribe for x in memberships]
        return myTribes

    @classmethod
    def available_tribes_for(cls, user):
        myTribes=TribeMember.tribes_for(user)
        tribes= Tribe.objects.all()
        availableTribes=[tribe for tribe in tribes if tribe not in myTribes and user != tribe.chieftain]
        return availableTribes

    def __str__(self):
        return f"{self.member.username} becomes member of {self.tribe.tribeName} tribe"

class Playlist(TimeStamped):
    tribe = models.ForeignKey(Tribe, on_delete=models.CASCADE, unique=False)
    name = models.CharField(max_length=128, unique=True, blank=False)
    description = models.TextField()
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='creator')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Tribe {self.tribe}: playlist {self.name}"

class Message(TimeStamped):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    tribe = models.ForeignKey(Tribe, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender.username} wrote a message in {self.tribe.tribeName} tribe"

class Track(TimeStamped):
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE, related_name="playlist", unique=False) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist = models.CharField(max_length=1200)
    title = models.CharField(max_length=1200)
    url = models.CharField(max_length=1200)
    duration = models.CharField(max_length=1200)
    likes=models.IntegerField(default=0)
    comments=models.IntegerField(default=0)

    def like_score(self):
        return self.like_set.filter(value=True).count()
    
    def comment_score(self):
        return self.comment_set.count()
    
    def like_by(self, user):
        if user.is_authenticated:
            return Like.objects.filter(user=user, track=self).first()
        else:
            return None


    def __str__(self):
        return f"{self.title} track added to {self.playlist.name} playlist"

class Like(TimeStamped):
    track = models.ForeignKey(Track, on_delete=models.CASCADE, unique=False) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value= models.BooleanField(null=False, default=False)

    class Meta:
        constraints=[
            models.UniqueConstraint(name='user_like',fields=['track','user'])
        ]

    def __str__(self):
        return f"{self.user.username} liked  track {self.track.title}"

class Comment(TimeStamped):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    text = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} wrote a comment on track {self.track.title}"

Application/mysite/musicTribes/forms.py
from tkinter import Place
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from musicTribes.models import Playlist, Tribe, TribeMember, Message, Track, Comment

class UserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1' ,'password2' )

class Edit_User_Form(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email')

class TribeForm(forms.ModelForm):
    class Meta:
        model=Tribe
        fields=['tribeName','tribeLogo','genre']

class JoinForm(forms.ModelForm):
    class Meta:
        model=TribeMember
        fields=['tribe','member']

class PlaylistForm(forms.ModelForm):
    class Meta:
        model=Playlist
        fields = ['name', 'description']
        
class MessageForm(forms.ModelForm):
    class Meta:
        model=Message
        fields = ['message']

class TrackForm(forms.ModelForm):
    class Meta:
        model=Track
        fields = ['artist', 'title', 'url', 'duration']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=['text']
      

Application/mysite/musicTribes/views.py
import json
import logging
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse

from musicTribes.models import Playlist, Tribe, TribeMember, Message, Track, Like, Comment
from .forms import JoinForm, PlaylistForm, TribeForm, MessageForm, TrackForm, CommentForm

def index(request):
    tribes = Tribe.objects.order_by('-id')
    if(request.user.is_authenticated):
        chieftainTribes = Tribe.tribesChieftain_for(request.user)
        myTribes= TribeMember.tribes_for(request.user)
        notMyTribes= TribeMember.available_tribes_for(request.user)
        context = { 'tribes': tribes,
            'myTribes': myTribes,
            'notMyTribes': notMyTribes,
            'chieftainTribes': chieftainTribes}
    else:
         context = { 'tribes': tribes}
    return render(request, 'app/index.html', context)


def create_tribe(request):
    if request.method=='POST':
        form = TribeForm(request.POST)
        if form.is_valid():
            saved_tribe=form.save(commit=False)
            saved_tribe.chieftain=request.user
            saved_tribe.save()
            return HttpResponseRedirect(reverse('MusicTribes:detail', args=(saved_tribe.id,)))
    else:
        form=TribeForm()
    context={'form':form, 'action': 'create'}
    return render(request, 'app/create_tribe.html',context)

def detail(request, tribe_id):
    tribe = get_object_or_404(Tribe,pk=tribe_id)
    playlists = Playlist.objects.order_by('-id')
    tribeMembers = TribeMember.objects.all()
    messages = Message.objects.all()
    if(request.user.is_authenticated):
        myTribes= TribeMember.tribes_for(request.user)
        context = {'myTribes': myTribes,
                    'tribe': tribe,
                    'playlists': playlists,
                    'tribeMembers': tribeMembers,
                    'messages': messages}
    else:
        context = {'tribe': tribe,
                    'playlists': playlists,
                    'tribeMembers': tribeMembers,
                    'messages': messages}
    return render(request, 'app/detail.html', context)

def join_tribe(request, tribe_id):
     if request.method=='POST':
        form = JoinForm(request.POST)
        if form.is_valid():
            saved_tribe=form.save(commit=False)
            saved_tribe.member=request.user
            saved_tribe.save()
            return HttpResponseRedirect(reverse('MusicTribes:index'))

def add_playlist(request, tribe_id):
    tribe = get_object_or_404(Tribe,pk=tribe_id)
    if request.method=='POST':
        form = PlaylistForm(request.POST)
        if form.is_valid():
            saved_playlist=form.save(commit=False)
            saved_playlist.tribe=tribe
            saved_playlist.creator=request.user
            saved_playlist.save()
            return HttpResponseRedirect(reverse('MusicTribes:detail', args=(tribe.id,)))
    else:
        form=PlaylistForm()
    context={'form':form, 'action': 'create'}
    return render(request, 'app/add_playlist.html',context)

def delete_playlist(request, playlist_id):
    playlist=get_object_or_404(Playlist, pk=playlist_id)
    if request.method=='POST' and request.user.is_authenticated:
        playlist.delete()
    return HttpResponseRedirect(reverse('MusicTribes:detail', args=(playlist.tribe.id,)))

def edit_playlist(request, playlist_id):
    playlist=get_object_or_404(Playlist, pk=playlist_id)
    if request.method=='POST':
        form = PlaylistForm(request.POST, instance=playlist)
        if form.is_valid():
            saved_playlist=form.save()
            return HttpResponseRedirect(reverse('MusicTribes:detail', args=(saved_playlist.tribe.id,)))
    else:
        form=PlaylistForm(instance=playlist)
    context={'form':form, 'action':'update'}
    return render(request, 'app/add_playlist.html',context)

def kick_user(request, tribeMember_id):
    tribeMember=get_object_or_404(TribeMember, pk=tribeMember_id)
    if request.method=='POST' and request.user.is_authenticated:
        tribeMember.delete()
    return HttpResponseRedirect(reverse('MusicTribes:detail', args=(tribeMember.tribe.id,)))

def add_message(request, tribe_id):
    tribe= get_object_or_404(Tribe, pk=tribe_id)
    if request.method=='POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            saved_message=form.save(commit=False)
            saved_message.tribe=tribe
            saved_message.sender= request.user
            saved_message.save()
            return HttpResponseRedirect(reverse('MusicTribes:detail', args=(tribe.id,)))

def delete_message(request, message_id, tribe_id):
    messsage=get_object_or_404(Message, pk=message_id)
    tribe=get_object_or_404(Tribe, pk=tribe_id)
    if request.method=='POST' and request.user == tribe.chieftain:
        messsage.delete()
    return HttpResponseRedirect(reverse('MusicTribes:detail', args=(messsage.tribe.id,)))

def playlist_detail(request, playlist_id, tribe_id):
    playlist = get_object_or_404(Playlist,pk=playlist_id)
    tracks = Track.objects.filter(playlist=playlist)
    tribe= get_object_or_404(Tribe, pk=tribe_id)
    likes=[track.like_by(request.user) for track in tracks]
    comments = Comment.objects.all()
    if(request.user.is_authenticated): 
        myTribes= TribeMember.tribes_for(request.user)
        context = {'tracks_with_likes': zip(tracks,likes),
                    'myTribes': myTribes,
                    'tribe': tribe,
                    'playlist': playlist,
                    'comments': comments}
    else:
        context = {'playlist': playlist,
                    'tribe': tribe,
                    'tracks_with_likes': zip(tracks,likes),
                    'comments': comments}
    return render(request, 'app/playlist_detail.html', context)

def add_track(request, tribe_id, playlist_id):
    tribe = get_object_or_404(Tribe,pk=tribe_id)
    playlist = get_object_or_404(Playlist,pk=playlist_id)
    if request.method=='POST':
        form = TrackForm(request.POST)
        if form.is_valid():
            saved_track=form.save(commit=False)
            saved_track.playlist=playlist
            saved_track.user=request.user
            saved_track.save()
            return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(playlist.id, tribe.id)))
    else:
        form=TrackForm()
    context={'form':form, 'action': 'create'}
    return render(request, 'app/add_track.html',context)

def like_track(request, track_id):
    track=get_object_or_404(Track, pk=track_id)
    if request.user.is_authenticated:
        like= Like.objects.filter(user=request.user, track=track).first()
        if like:
            like.delete()
            return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))
        else:
            like=Like(user=request.user, track=track, value=True)
        try:
            like.full_clean()
            like.save()
        except:
            return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))
        else:
            return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))
    else:
        return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))

def add_comment(request, track_id):
    track=get_object_or_404(Track, pk=track_id)
    if request.method == 'POST'and request.user.is_authenticated:
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.track=track
            comment.user= request.user
            comment.save()
            return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))
        else:
            return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))
    else:
         return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))

def delete_track(request, track_id):
    track=get_object_or_404(Track, pk=track_id)
    if request.method=='POST' and request.user.is_authenticated:
        track.delete()
    return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))

def delete_comment(request, track_id, comment_id):
    track=get_object_or_404(Track, pk=track_id)
    comment=get_object_or_404(Comment, pk=comment_id)
    if request.method=='POST':
        comment.delete()
    #return HttpResponseRedirect(reverse('MusicTribes:index'))
    return HttpResponseRedirect(reverse('MusicTribes:playlist_detail', args=(track.playlist.id, track.playlist.tribe.id)))

Application/mysite/musicTribes/templates/app/add_playlist.html
{% extends 'app/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            {% if action == "create" %}
                <h2 class="text-center">Submit new Playlist</h2>
            {%else%}
                <h2 class="text-center">Edit Playlist</h2>
            {% endif %}
        </div>
    </div>

    <form method="post" accept-charset="utf-8">
        {% csrf_token %}
        
        {% include 'includes/bs4_form.html' with form=form %}

        <div class="row">
            <div class="col-md-8 mx-auto">
                <input type="submit" value="Submit" class="btn btn-primary">
            </div>
        </div>
    </form>
{% endblock content %}

Application/mysite/musicTribes/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>

    {% block extrahead %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}">

  </head>
  <body>
    <div class="page-header text-light">
      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(226, 139, 18, 0.8);">
        <a class="navbar-brand" href="/">Music Tribes</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="#">Hi {{ user.username }}!</a>
              </li>
              {% if user.is_superuser or user.is_staff %}
              <li class="nav-item">
                <a class="nav-link" href="/admin">Admin Dashboard</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile' %}">Edit_User</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">Singup</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    <div class="content container bg-light mt-5">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron h-100">
            <div class="row">
              <div class="col-md-4 offset-md-4">
                <div class="container">
                  <h1 class="display-4" style="background-color:rgba(238, 204, 67, 0.8); ">Music Tribes</h1>
                  <p class="lead"></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    <div class="row mt-5" style="background-color:rgba(226, 139, 18, 0.8);">
      <div class="col-md-5 offset-md-4 my-5">
        <h4>2022 © MusicTribes. All rights reserved.</h4>
      </div>
    </div>
  </body>
</html>

Application/mysite/musicTribes/templates/app/detail.html
{% extends 'app/base.html' %}

{% block content %}
<div  style="background-color: rgba(214, 116, 92, 0.8); border-radius: 25px;">
    <div class="row text-center mt-3 ml-5 mr-5">
        <div class="col-md-12">
            <img class="rounded-circle account-img mt-3" style="width: 100px; height: 100px;" src="{{ tribe.tribeLogo.url }}">
        </div>
    </div>
    <div class="row text-center ml-5 mr-5">
        <div class="col-md-12">
            <h1>{{ tribe.tribeName }}</h1>
        </div>
    </div>
    </div>

    {% for myTribe in myTribes %}
        {% if tribe == myTribe %}
            <div class="row mt-3">
                <div class="col-md-6 text-right pr-1">
                    <h3>Joined</h3>
                </div>
                <div class="col-md-3 text-left align-middle pl-0">
                    <div><i class="fa-solid fa-circle-check fa-2xl" style="color:green;"></i></div>
                </div>
                <div class="col-md-3 text-right">
                    {% for tribeMember in tribeMembers %}
                    {% if tribeMember.tribe == tribe and tribeMember.member == request.user %}
                    <form action="{% url 'MusicTribes:kick_user' tribeMember.id %}" method="post" role="form">
                        {% csrf_token %}
                        <input type="submit" value="Leave Tribe" class="btn btn-warning">
                    </form>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>   
        {% endif %}
    {% endfor %}

    {% if request.user == tribe.chieftain %}
        <a href="{% url 'MusicTribes:add_playlist' tribe.id %}" class="btn btn-warning my-3">Add new Playlist</a>
    {% endif %}

    <div class="row">
        <div class="col-md-8">
            <div class="row" style="background-color: rgba(240, 124, 22, 0.8); border-radius: 25px;">
                <div class="row m-2">
                    <div class="col-md-12">
                        <h1>Playlists: </h1>
                    </div>
                </div>
            <div class="row mt-3">
            {% for playlist in playlists %}
                {% if playlist.tribe == tribe %}
                    
                        <div class="col-md-4">
                            <p><a href="{% url 'MusicTribes:playlist_detail' playlist.id tribe.id %}" class="btn btn-warning ml-3">{{ playlist.name }}</a></p>
                        </div>
                        {% if tribe.chieftain == request.user  %}
                            <div class="col-md-4">
                                <form action="{% url 'MusicTribes:delete_playlist' playlist.id %}" method="post" role="form">
                                    {% csrf_token %}
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                </form>
                            </div>
                            <div class="col-md-4">
                                <a href="{% url 'MusicTribes:edit_playlist' playlist.id %}" class="btn btn-primary">Edit</a>
                            </div>
                        {% endif %}
                    
                {% endif %}
            {% endfor %}
            </div>
        </div>
        </div>
        <div class="col-md-4 text-center" style="background-color: rgba(238, 96, 67, 0.8); border-radius: 25px;">
            <h3>Tribe Members:</h3>
            <div class="row mb-3">
                <div class="col-md-6 offset-md-3" style="border:1px solid black;">
                    <p>{{ tribe.chieftain }}(chieftain)</p>
                </div>
            </div>
            {% for tribeMember in tribeMembers %}
                {% if tribeMember.tribe == tribe%}
                    <div class="row">
                        <div class="col-md-8">
                            <p>{{ tribeMember.member.username }}</p>
                        </div>
                        {% if tribe.chieftain == request.user %}
                            <div class="col-md-4">
                                <form action="{% url 'MusicTribes:kick_user' tribeMember.id %}" method="post" role="form">
                                    {% csrf_token %}
                                    <input type="submit" value="Kick" class="btn btn-danger">
                                </form>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="mb-3 p-2" style="border:1px solid black;">
                <h3>Chatbox</h3>
                {% for message in messages %}
                    {% if message.tribe == tribe %}
                        {% if tribe.chieftain == message.sender %}
                        <div class="m-3">
                            <div class="row" style="background-color: rgb(214, 43, 80)">
                                <p class="pl-1 mb-0"> 
                                    <img class="rounded-circle account-img" src="{{ message.sender.profile.image.url }}" style="width: 30px; height: 30px">
                                    {{ message.sender }} (chieftain)
                                </p>
                            </div>
                            <div class="row" style="background-color: rgb(214, 43, 80)">
                                <p class="pl-5 mt-0 mb-0" style="font-size: 10px;">{{ message.timestamp }}</p>
                            </div>
                            <div class="row" style="background-color: rgb(229, 149, 149)">
                                <p class="pl-3 mt-2">{{ message.message }}</p>
                                <div class="ml-auto">
                                    {% if tribe.chieftain == request.user or user.is_superuser %}
                                        <form action="{% url 'MusicTribes:delete_message' message.id tribe.id%}" method="post" role="form">
                                            {% csrf_token %}
                                            <input  type="submit" value="Delete" class="btn btn-danger mr-1 mt-1">
                                        </form>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% else %}
                        <div class="m-3">
                            <div class="row" style="background-color: rgb(113, 113, 230)">
                                <p class="pl-1 mb-0"> 
                                    <img class="rounded-circle account-img" src="{{ message.sender.profile.image.url }}" style="width: 30px; height: 30px">
                                    {{ message.sender }}
                                </p>
                            </div>
                            <div class="row" style="background-color: rgb(113, 113, 230)">
                                <p class="pl-5 mt-0 mb-0" style="font-size: 10px;">{{ message.timestamp }}</p>
                            </div>
                            <div class="row" style="background-color: rgb(162, 162, 235)">
                                <p class="pl-3 mt-2">{{ message.message }}</p>
                                <div class="ml-auto">
                                    {% if tribe.chieftain == request.user or user.is_superuser %}
                                        <form action="{% url 'MusicTribes:delete_message' message.id tribe.id%}" method="post" role="form">
                                            {% csrf_token %}
                                            <input style="height: 30px" type="submit" value="Delete" class="btn btn-danger mr-1 mt-1">
                                        </form>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                

                {% if user.is_authenticated %}
                <div class="col-md-12">
                    <form action="{% url 'MusicTribes:add_message' tribe.id %}" method="post" role="form">
                        {% csrf_token %}
                        <input id="message" type="text" name="message" class="mt-3" placeholder="Enter your comment">
                        <input type="submit" value="Submit" class="btn btn-primary">
                    </form>
                </div>
                {% endif %}
            </div>

        </div>
    </div>
{% endblock %}